__author__ = 'admin'


SCM_DB_SERVER = ''
SCM_DB_PORT = ''
SCM_DB_USER = ''
SCM_DB_PASSWORD = ''
SCM_DB_DATABASE = ''


# SCM_DB_SERVER = "192.168.250.11"
# SCM_DB_PORT = 1433
# SCM_DB_USER = "scm"
# SCM_DB_PASSWORD = "Scm20140607PI"
# SCM_DB_DATABASE = "myshopcmstock"